/home/samuel_j_fangman/scrapecrypto/scrape_crypto.py:21: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  data = pd.io.json.json_normalize(response.json()['data'])
/home/samuel_j_fangman/scrapecrypto/scrape_crypto.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  info = pd.io.json.json_normalize(response.json()['info'])
Scraping Coinlore.net for ticker data...
Scrape time = 2020-02-18 00:14:54.029427
Traceback (most recent call last):
  File "run-scrape.py", line 3, in <module>
    sc.scrape()
  File "/home/samuel_j_fangman/scrapecrypto/scrape_crypto.py", line 51, in scrape
    store_data(df)
  File "/home/samuel_j_fangman/scrapecrypto/scrape_crypto.py", line 38, in store_data
    collection.insert_many(df.to_dict('records'))
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/collection.py", line 758, in insert_many
    blk.execute(write_concern, session=session)
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/bulk.py", line 511, in execute
    return self.execute_command(generator, write_concern, session)
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/bulk.py", line 344, in execute_command
    with client._tmp_session(session) as s:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1823, in _tmp_session
    s = self._ensure_session(session)
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1810, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1763, in __start_session
    server_session = self._get_server_session()
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/mongo_client.py", line 1796, in _get_server_session
    return self._topology.get_server_session()
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/topology.py", line 485, in get_server_session
    None)
  File "/home/samuel_j_fangman/.local/lib/python3.6/site-packages/pymongo/topology.py", line 209, in _select_servers_loop
    self._error_message(selector))
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
